---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aptos-validator.fullname" . }}-haproxy
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
data:
  haproxy.cfg: |-
{{ (tpl (.Files.Get "files/haproxy.cfg") .) | indent 4 }}
  blocked.ips: ""
