---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-validator.fullname" . }}-validator-lb
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
  {{- with .Values.service.validator.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "aptos-validator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: haproxy
  ports:
  - name: validator
    port: 6180
  - name: metrics
    port: 9101
    targetPort: 9102
  {{- if .Values.validator.exposeRestApi }}
  - name: api
    port: 80
    targetPort: 8180
  {{- end }}
  type: {{ .Values.service.external.type }}
  externalTrafficPolicy: Local
  {{- with .Values.service.validator.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
