apiVersion: v1
kind: Service
metadata:
  name: {{ include "teku-beacon.fullname" . }}-rpc
  labels:
    {{- include "teku-beacon.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5051
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "teku-beacon.selectorLabels" . | nindent 4 }}
