apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssv-node.fullname" . }}-metrics
  labels:
    {{- include "ssv-node.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.MetricsAPIPort }}
      name: metrics
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "ssv-node.selectorLabels" . | nindent 4 }}
