apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solana-exporter.fullname" . }}-config
  labels:
    {{- include "solana-exporter.labels" . | nindent 4 }}
data:
  config.toml: |-
    {{- .Values.config | nindent 4 }}
  entrypoint.sh: |-
    #! /bin/bash
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt update && apt install -y ca-certificates
    exec "$@"
