apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.serviceName }}{{ .Values.serviceName }}{{ else }}{{ include "solana-exporter.fullname" . }}{{ end }}
  labels:
    {{- include "solana-exporter.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 9179
      name: metrics
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "solana-exporter.selectorLabels" . | nindent 4 }}
