---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solana-accounts
spec:
  capacity:
    storage: 800Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/solana/accounts
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - scw-solana-testnet-bare-metal-b12aa14f73fe4c91
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solana-accounts
  namespace: solana-testnet
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
  volumeName: solana-accounts
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solana-ledger
spec:
  capacity:
    storage: 800Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/solana/ledger
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - scw-solana-testnet-bare-metal-b12aa14f73fe4c91
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solana-ledger
  namespace: solana-testnet
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
  volumeName: solana-ledger
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solana-config
spec:
  capacity:
    storage: 800Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /data/solana/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - scw-solana-testnet-bare-metal-b12aa14f73fe4c91
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: solana-config
  namespace: solana-testnet
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
  volumeName: solana-config
