apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teku-validator.fullname" . }}-config
  labels:
    {{- include "teku-validator.labels" . | nindent 4 }}
data:
  config.yaml: |-
  {{- toYaml .Values.config | nindent 4 }}
