---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aptos-validator.fullname" . }}
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "files/configs/*.yaml").AsConfig . | indent 2 }}
