apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solana.fullname" . }}-keys
  labels:
    {{- include "solana.labels" . | nindent 4 }}
stringData:
  validator-keypair.json: |-
    {{ .Values.solana.validatorKeypair | nindent 4 }}
  vote-account-keypair.json: |-
    {{ .Values.solana.voteAccountKeypair | nindent 4 }}
