apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.serviceName }}{{ .Values.serviceName }}{{ else }}{{ include "solana.fullname" . }}{{ end }}
  labels:
    {{- include "solana.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5052
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "solana.selectorLabels" . | nindent 4 }}
