apiVersion: v1
kind: Service
metadata:
  name: {{ include "solana.fullname" . }}-metrics
  labels:
    {{- include "solana.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 5054
      name: metrics
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "solana.selectorLabels" . | nindent 4 }}
