apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "solana.fullname" . }}
  labels:
    {{- include "solana.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "solana.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategyType }}
    {{- if (eq "OnDelete" .Values.updateStrategyType) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "solana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "solana.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "solana.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /ledger
              name: ledger
            - mountPath: /accounts
              name: accounts
            - mountPath: /root/.config/solana/
              name: config
            - mountPath: /entrypoint
              name: entrypoint
          command:
            - /entrypoint/entrypoint.sh
          args:
            - solana-validator
            - --entrypoint=entrypoint.{{ .Values.solana.cluster }}.solana.com:8001
            - --rpc-port=8899
            - --dynamic-port-range=8000-8010
            - --identity=/root/.config/solana/validator-keypair.json
            - --vote-account=/root/.config/solana/vote-account-keypair.json
            - --accounts=/accounts
            - --ledger=/ledger
            - --limit-ledger-size
            - --log=-
          {{- range $key, $value := .Values.extraArgs }}
            {{- /* Accept keys without values or with false as value */}}
            {{- if eq ($value | quote | len) 2 }}
            - --{{ $key }}
            {{- else }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
          ports:
            - name: rpc
              containerPort: 8899
              protocol: TCP
              hostPort: 8899
            - name: rpc-ws
              containerPort: 8900
              protocol: TCP
              hostPort: 8900
            - name: dynamic-0-tcp
              containerPort: 8000
              protocol: TCP
              hostPort: 8000
            - name: dynamic-1-tcp
              containerPort: 8001
              protocol: TCP
              hostPort: 8001
            - name: dynamic-2-tcp
              containerPort: 8002
              protocol: TCP
              hostPort: 8002
            - name: dynamic-3-tcp
              containerPort: 8003
              protocol: TCP
              hostPort: 8003
            - name: dynamic-4-tcp
              containerPort: 8004
              protocol: TCP
              hostPort: 8004
            - name: dynamic-5-tcp
              containerPort: 8005
              protocol: TCP
              hostPort: 8005
            - name: dynamic-6-tcp
              containerPort: 8006
              protocol: TCP
              hostPort: 8006
            - name: dynamic-7-tcp
              containerPort: 8007
              protocol: TCP
              hostPort: 8007
            - name: dynamic-8-tcp
              containerPort: 8008
              protocol: TCP
              hostPort: 8008
            - name: dynamic-9-tcp
              containerPort: 8009
              protocol: TCP
              hostPort: 8009
            - name: dynamic-0-udp
              containerPort: 8000
              protocol: UDP
              hostPort: 8000
            - name: dynamic-1-udp
              containerPort: 8001
              protocol: UDP
              hostPort: 8001
            - name: dynamic-2-udp
              containerPort: 8002
              protocol: UDP
              hostPort: 8002
            - name: dynamic-3-udp
              containerPort: 8003
              protocol: UDP
              hostPort: 8003
            - name: dynamic-4-udp
              containerPort: 8004
              protocol: UDP
              hostPort: 8004
            - name: dynamic-5-udp
              containerPort: 8005
              protocol: UDP
              hostPort: 8005
            - name: dynamic-6-udp
              containerPort: 8006
              protocol: UDP
              hostPort: 8006
            - name: dynamic-7-udp
              containerPort: 8007
              protocol: UDP
              hostPort: 8007
            - name: dynamic-8-udp
              containerPort: 8008
              protocol: UDP
              hostPort: 8008
            - name: dynamic-9-udp
              containerPort: 8009
              protocol: UDP
              hostPort: 8009
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ include "solana.fullname" . }}-entrypoint
            defaultMode: 0777
  {{- if not .Values.persistence.enabled }}
        - name: ledger
          emptyDir: {}
        - name: accounts
          emptyDir: {}
        - name: config
          emptyDir: {}
  {{- else }}
        - name: ledger
          persistentVolumeClaim:
            {{- with .Values.persistence.ledger.existingClaim }}
            claimName: {{ tpl . $ }}
            {{- end }}
        - name: accounts
          persistentVolumeClaim:
            {{- with .Values.persistence.accounts.existingClaim }}
            claimName: {{ tpl . $ }}
            {{- end }}
        - name: config
          persistentVolumeClaim:
            {{- with .Values.persistence.config.existingClaim }}
            claimName: {{ tpl . $ }}
            {{- end }}
  {{- end }}
