apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nethermind.fullname" . }}-entrypoint
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #! /bin/bash

    set -e

    exec "$@"
