apiVersion: v1
kind: Service
metadata:
  name: {{ include "nethermind.fullname" . }}-rpc
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8545
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nethermind.selectorLabels" . | nindent 4 }}
