apiVersion: v1
kind: Service
metadata:
  name: {{ include "nethermind.fullname" . }}-metrics
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 9091
      name: metrics
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "nethermind.selectorLabels" . | nindent 4 }}
