apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.serviceName }}{{ .Values.serviceName }}{{ else }}{{ include "nethermind.fullname" . }}{{ end }}
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8545
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "nethermind.selectorLabels" . | nindent 4 }}
