apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nethermind.fullname" . }}
  labels:
    {{- include "nethermind.labels" . | nindent 4 }}
spec:
  serviceName: {{ if .Values.serviceName }}{{ .Values.serviceName }}{{ else }}{{ include "nethermind.fullname" . }}{{ end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategyType }}
    {{- if (eq "OnDelete" .Values.updateStrategyType) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "nethermind.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nethermind.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nethermind.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.config.datadir }}
              name: data
            - mountPath: /entrypoint
              name: entrypoint
          command:
            - /entrypoint/entrypoint.sh
          args:
            - ./Nethermind.Runner
            - --Init.WebSocketsEnabled=true
            - --JsonRpc.Enabled=true
            - --JsonRpc.Host=0.0.0.0
            - --Metrics.Enabled=true
            - --Init.BaseDbPath={{ .Values.config.datadir }}
          {{- range $key, $value := .Values.extraArgs }}
            {{- /* Accept keys without values or with false as value */}}
            {{- if eq ($value | quote | len) 2 }}
            - --{{ $key }}
            {{- else }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
          ports:
            - name: p2p-tcp
              containerPort: {{ .Values.service.p2p.tcp.port}}
              protocol: TCP
            {{- if .Values.service.p2p.enableHostPort }}
              hostPort: {{ .Values.service.p2p.tcp.port }}
            {{- end }}
            - name: p2p-udp
              containerPort: {{ .Values.service.p2p.udp.port}}
              protocol: UDP
            {{- if .Values.service.p2p.enableHostPort }}
              hostPort: {{ .Values.service.p2p.udp.port }}
            {{- end }}
            - name: metrics
              containerPort: 9091
              protocol: TCP
            - name: http
              containerPort: 8545
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ include "nethermind.fullname" . }}-entrypoint
            defaultMode: 0777
  {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            {{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
            {{- end }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "nethermind.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
  {{- end }}
