apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lighthouse-validator.fullname" . }}-entrypoint
  labels:
    {{- include "lighthouse-validator.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    #! /bin/bash

    set -e

    exec "$@"
