{{- if and .Values.init.enabled ( eq .Values.init.type "secretsmanager" ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lighthouse-validator.fullname" . }}-init-aws-secretsmanager
  labels:
    {{- include "lighthouse-validator.labels" . | nindent 4 }}
data:
  init.sh: |-
    #! /usr/bin/env bash
    set -e

    yum -y install jq

    for secret in $(jq -r '.[]' /init/secret-ids)
    do

      SECRET_STRING=$(aws secretsmanager get-secret-value --secret-id $secret --output json | jq '.SecretString | fromjson')
      PUBKEY=$(jq -r .pubkey <<< $SECRET_STRING)
      mkdir -p /keys/0x${PUBKEY}
      jq -r .key <<< $SECRET_STRING | base64 -d > /keys/0x${PUBKEY}/voting-keystore.json
      jq -r .password <<< $SECRET_STRING > /secrets/0x${PUBKEY}

    done
  secret-ids: |-
    {{- toJson .Values.init.secretsmanager.secretIds | nindent 4 }}
{{- end }}
