apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse-validator.fullname" . }}-rpc
  labels:
    {{- include "lighthouse-validator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 5062
      name: http
      targetPort: http
      protocol: TCP
  selector:
    {{- include "lighthouse-validator.selectorLabels" . | nindent 4 }}
