apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lighthouse-validator.fullname" . }}
  labels:
    {{- include "lighthouse-validator.labels" . | nindent 4 }}
spec:
  serviceName: {{ if .Values.serviceName }}{{ .Values.serviceName }}{{ else }}{{ include "lighthouse-validator.fullname" . }}{{ end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategyType }}
    {{- if (eq "OnDelete" .Values.updateStrategyType) }}
    rollingUpdate: null
    {{- end }}
  selector:
    matchLabels:
      {{- include "lighthouse-validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lighthouse-validator.selectorLabels" . | nindent 8 }}
        checksum/entrypoint: {{ include (print $.Template.BasePath "/configmap-entrypoint.yaml") . | sha256sum | trunc 63 }}
        {{- if and .Values.init.enabled ( eq .Values.init.type "secretsmanager" ) }}
        checksum/init: {{ include (print $.Template.BasePath "/configmap-init-aws-secretmanager.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lighthouse-validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if and .Values.init.enabled ( eq .Values.init.type "secretsmanager" ) }}
      initContainers:
        - name: load-validator-keys
          image: "{{ .Values.additionalImages.awscli.repository }}:{{ .Values.additionalImages.awscli.tag }}"
          imagePullPolicy: {{ .Values.additionalImages.awscli.pullPolicy }}
          command:
            - /init/init.sh
          volumeMounts:
            - mountPath: /keys
              name: keys
            - mountPath: /secrets
              name: secrets
            - mountPath: /init
              name: init
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.config.datadir }}
              name: data
            - mountPath: /entrypoint
              name: entrypoint
            {{- if .Values.ephemeral.enabled }}
            - mountPath: {{ .Values.config.datadir }}/secrets
              name: secrets
            - mountPath: {{ .Values.config.datadir }}/validators/keys
              name: keys
            {{- end }}
          {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
          env:
          {{- if .Values.extraEnvs }}
            {{- toYaml .Values.extraEnvs | nindent 12 }}
          {{- end }}
          command:
            - /entrypoint/entrypoint.sh
          args:
            - lighthouse
            - validator_client
            - --datadir={{ .Values.config.datadir }}
            - --metrics
            - --metrics-address=0.0.0.0
          {{- range $key, $value := .Values.extraArgs }}
            {{- /* Accept keys without values or with false as value */}}
            {{- if eq ($value | quote | len) 2 }}
            - --{{ $key }}
            {{- else }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
          ports:
            - name: metrics
              containerPort: 5064
              protocol: TCP
            - name: http
              containerPort: 5062
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: {{ include "lighthouse-validator.fullname" . }}-entrypoint
            defaultMode: 0777
        {{- if .Values.ephemeral.enabled }}
        - name: keys
          emptyDir:
            medium: Memory
        - name: secrets
          emptyDir:
            medium: Memory
        {{- end }}
        {{- if and .Values.init.enabled ( eq .Values.init.type "secretsmanager" ) }}
        - name: init
          configMap:
            name: {{ include "lighthouse-validator.fullname" . }}-init-aws-secretsmanager
            defaultMode: 0755
        {{- end }}
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
  {{- if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            {{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
            {{- end }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "lighthouse-validator.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
  {{- end }}
