apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web3signer.fullname" . }}-config
  labels:
    {{- include "web3signer.labels" . | nindent 4 }}
data:
  config.yaml: |-
  {{- toYaml .Values.config | nindent 4 }}
