apiVersion: v1
kind: Service
metadata:
  name: {{ include "web3signer.fullname" . }}-metrics
  labels:
    {{- include "web3signer.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: true
  type: {{ .Values.service.type }}
  ports:
    - port: 9001
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "web3signer.selectorLabels" . | nindent 4 }}
