---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "aptos-validator.fullname" . }}-validator
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "aptos-validator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: validator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # AptosNet from HAproxy
  - from:
    - podSelector:
        matchLabels:
          {{- include "aptos-validator.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/name: haproxy
    ports:
    - protocol: TCP
      port: 6180
    - protocol: TCP
      port: 9101
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - protocol: TCP
      port: 9101
  {{- if .Values.validator.exposeRestApi }}
  # REST API from HAproxy
    - protocol: TCP
      port: 8080
  {{- end }}
  # AptosNet from local full nodes
  - from:
    - podSelector:
        matchLabels:
          {{- include "aptos-validator.selectorLabels" . | nindent 10 }}
          app.kubernetes.io/name: fullnode
    ports:
    - protocol: TCP
      port: 6181
  egress:
  # AptosNet to other validators
  - ports:
    - protocol: TCP
      port: 6180
  # DNS
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
  # Enable HTTPS telemetry
  - ports:
    - protocol: TCP
      port: 443

