---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aptos-validator.fullname" . }}-validator-e{{ .Values.chain.era }}
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.validator.storage.class }}
  resources:
    requests:
      storage: {{ .Values.validator.storage.size }}

