---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-validator.fullname" . }}-validator
  labels:
    {{- include "aptos-validator.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "aptos-validator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: validator
  ports:
  - name: validator
    port: 6180
  - name: fullnode
    port: 6181
  - name: metrics
    port: 9101
  {{- if .Values.validator.exposeRestApi }}
  - name: api
    port: 8080
  {{- end }}

