apiVersion: v1
kind: Service
metadata:
  name: {{ include "erigon.fullname" . }}-rpc
  labels:
    {{- include "erigon.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      name: rpc
      targetPort: rpc
      protocol: TCP
  selector:
    {{- include "erigon.selectorLabels" . | nindent 4 }}
