apiVersion: v1
kind: Service
metadata:
  name: {{ include "erigon.fullname" . }}
  labels:
    {{- include "erigon.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.rpc.port }}
      name: rpc
      targetPort: rpc
      protocol: TCP
  selector:
    {{- include "erigon.selectorLabels" . | nindent 4 }}
