apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "erigon.fullname" . }}
  labels:
    {{- include "erigon.labels" . | nindent 4 }}
spec:
  {{- if .Values.podManagementPolicy }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  {{- end }}
  serviceName: {{ include "erigon.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "erigon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "erigon.selectorLabels" . | nindent 8 }}
    spec:
      shareProcessNamespace: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "erigon.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        {{- if .Values.erigon.enabled }}
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.erigon.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: {{ .Values.erigon.datadir }}
              name: data
          command:
            - erigon
          args:
            - --datadir={{ .Values.erigon.datadir }}
            - --port={{ .Values.service.p2p.port }}
            - --p2p.eth65.port={{ .Values.service.p2p.portEth65 }}
            {{- toYaml .Values.erigon.defaultArgs | nindent 12 }}
          {{- range $key, $value := .Values.erigon.extraArgs }}
            {{- /* Accept keys without values or with false as value */}}
            {{- if eq ($value | quote | len) 2 }}
            - --{{ $key }}
            {{- else }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
          ports:
            - name: p2p-tcp
              containerPort: {{ .Values.service.p2p.port }}
              protocol: TCP
            {{- if .Values.service.p2p.enableHostPort }}
              hostPort: {{ .Values.service.p2p.port }}
            {{- end }}
            - name: p2p-udp
              containerPort: {{ .Values.service.p2p.port }}
              protocol: UDP
            {{- if .Values.service.p2p.enableHostPort }}
              hostPort: {{ .Values.service.p2p.port }}
            {{- end }}
            - name: p2p-eth65-tcp
              containerPort: {{ .Values.service.p2p.portEth65 }}
              protocol: TCP
            {{- if .Values.service.p2p.enableHostPort }}
              hostPort: {{ .Values.service.p2p.portEth65 }}
            {{- end }}
            - name: p2p-eth65-udp
              containerPort: {{ .Values.service.p2p.portEth65 }}
              protocol: UDP
            {{- if .Values.service.p2p.enableHostPort }}
              hostPort: {{ .Values.service.p2p.portEth65 }}
            {{- end }}
            - name: metrics
              containerPort: 6060
            - name: pprof
              containerPort: 6061
            - name: private-api
              containerPort: 9090
          resources:
            {{- toYaml .Values.erigon.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.rpcdaemon.enabled }}
        - name: {{ .Chart.Name }}-rpc
          securityContext:
            {{- toYaml .Values.rpcdaemon.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.erigon.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.erigon.datadir }}
              name: data
          {{- end }}
          command:
            - rpcdaemon
          args:
          {{- if .Values.erigon.enabled }}
            - --datadir={{ .Values.erigon.datadir }}
          {{- end }}
            {{- toYaml .Values.erigon.defaultArgs | nindent 12 }}
          {{- range $key, $value := .Values.rpcdaemon.extraArgs }}
            {{- /* Accept keys without values or with false as value */}}
            {{- if eq ($value | quote | len) 2 }}
            - --{{ $key }}
            {{- else }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- end }}
          ports:
            - name: rpc
              containerPort: 8545
              protocol: TCP
          resources:
            {{- toYaml .Values.rpcdaemon.resources | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.erigon.enabled }}
  {{- if not .Values.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
  {{- else if .Values.persistence.existingClaim }}
      volumes:
        - name: data
          persistentVolumeClaim:
            {{- with .Values.persistence.existingClaim }}
            claimName: {{ tpl . $ }}
            {{- end }}
  {{- else }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "erigon.selectorLabels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode | quote }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
