apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}-rpc
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8545
      name: http-rpc
      targetPort: http-rpc
      protocol: TCP
    - port: 8546
      name: ws-rpc
      targetPort: ws-rpc
      protocol: TCP
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
