apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}-metrics
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    - port: 6060
      name: metrics
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
